### ISSUE TITLE
Sharp dependency issue when running on a separate rPi4 4GB

### ISSUE THREAD

**Issue by caliKev** [jakowenko/double-take#109]
Hi,

I'm having trouble running this container on a separate rPi4 4GB device. It looks like a sharp dependency issue. I'm happy to help troubleshoot, but I don't have a lot of experience building containers.

pi@raspberrypi:~/double-take $ docker-compose up
Starting double-take ... done
Attaching to double-take
double-take    | /double-take/api/node_modules/sharp/lib/constructor.js:32
double-take    |   throw new Error(error);
double-take    |   ^
double-take    | 
double-take    | Error: 
double-take    | Something went wrong installing the "sharp" module
double-take    | 
double-take    | Error relocating /usr/lib/libvips.so.42: __ctime64: symbol not found
double-take    | 
double-take    | - Remove the "node_modules/sharp" directory then run
double-take    |   "npm install --ignore-scripts=false --verbose sharp" and look for errors
double-take    | - Consult the installation documentation at https://sharp.pixelplumbing.com/install
double-take    | - Search for this error at https://github.com/lovell/sharp/issues
double-take    | 
double-take    |     at Object.<anonymous> (/double-take/api/node_modules/sharp/lib/constructor.js:32:9)
double-take    |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
double-take    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
double-take    |     at Module.load (internal/modules/cjs/loader.js:937:32)
double-take    |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
double-take    |     at Module.require (internal/modules/cjs/loader.js:961:19)
double-take    |     at require (internal/modules/cjs/helpers.js:92:18)
double-take    |     at Object.<anonymous> (/double-take/api/node_modules/sharp/lib/index.js:3:15)
double-take    |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
double-take    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
`

**Comment by jakowenko** [comment]
Thanks for reporting this. I have a Pi at home I will test with.

**Comment by jakowenko** [comment]
This is now released in `v1.4.0` and can be pulled from the `latest` tag as well.

Feel free to reopen if you run into any issues.

**Comment by caliKev** [comment]
Thanks again for the help. In the meantime I was able to get double-take working on my jetson. I am still struggling to get deep-stack working. I had it working a few months back.

Here is the output of the commands:

pi@raspberrypi:~ $ cat /sys/firmware/devicetree/base/model; echo
Raspberry Pi 4 Model B Rev 1.1
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
pi@raspberrypi:~ $ docker --version
Docker version 20.10.8, build 3967b7d
pi@raspberrypi:~ $
