### ISSUE TITLE
beta v1.1.0-aa030da:beta: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#111]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5937811/134472403-01cc4a4b-9759-49c2-ae70-33e61b470ac0.png)
**Version of Double Take**
v1.1.0-aa030da:beta

beta-issue?

---edit:
no problem in v1.0.0-39cb3c3:latest

**Comment by jakowenko** [comment]
I think this is related to the `cameras` and `types` I added to the filter menu. Can you also post a screenshot of the match page on the ui showing that table of the filters. Does your show the cameras and types?

![Screen Shot 2021-09-23 at 9 36 03 AM](https://user-images.githubusercontent.com/1081811/134517017-2b240996-3c07-4bce-ad41-947210051462.png)

**Comment by ozett** [comment]
i switched back in docker to the latest beta, to show you that screen.
now i cannot see any error anymore in the log? fixed?
v1.1.0-aa030da:beta
![image](https://user-images.githubusercontent.com/5937811/134557049-f9f23b23-6f26-49a2-bd19-3d1d499dedcb.png)

**Comment by jakowenko** [comment]
Ya, seems like it could be fixed. Did you do a `docker-compose down` originally to make sure the old containers were killed? Might have just been something weird when you updated the image.

**Comment by jakowenko** [comment]
I'm going to close this as I haven't heard of any more reports of it. Feel free to open if it's still present in the latest builds.
