### ISSUE TITLE
Compreface Fails to Connect When det_prob_threshold is Two Digits

### ISSUE THREAD

**Issue by xCJPECKOVERx** [jakowenko/double-take#136]
**Describe the bug**
Double-take fails to connect to Compreface when the 'det_prob_threshold' option has more than one digit. For example, the det_prob_threshold value of 0.9 will connect, but 0.95 will not.

**Version of Double Take**
`v1.5.1-ba20c69:latest`

**Expected behavior**
Either connect to Compreface with a det_prob_threshold value of 0.95, automatically round down, or warn of the limitation.

**Screenshots**
![image](https://user-images.githubusercontent.com/9089397/138031990-ac45ab04-2b77-4e48-b1fd-4f9fda24f64b.png)

![image](https://user-images.githubusercontent.com/9089397/138031436-58d84504-1342-4a4c-b8fc-65c06e1ad71c.png)

**Hardware**
 - OS: Docker(Unraid)

**Additional context**
Compreface returns error 400 when using a 2 digit det_prob_threshold, so it's possible this is a Compreface limitation. If that's the case, then documentation for this config option or automatically rounding this value would be helpful.

**Comment by jakowenko** [comment]
This was fixed in the latest release `v1.7.0`. If you encounter any other issues feel free to reopen to make a new issue.
