### ISSUE TITLE
[FEAT] detect also non-face objects?

### ISSUE THREAD

**Issue by Ocramius** [jakowenko/double-take#142]
## Context

I just spent some time configuring double-take, and I must say that the DX of it acting as a middle-actor between MQTT, Frigate and complex recognition engines is quite refreshing.

My setup is quite simple: an IP Cam tracks objects passing by in a hallway.

 * People (only from the knee down)
 * Pets (cats/dogs)
 * Wildlife 

While I managed to make this work with the faces of some subjects, the IP Camera is specifically placed, in respect of personal privacy, in such a way that faces are not visible (camera video feed does not include anything from torso up).

I attempted to train the model against photos of legs (people passing by - clothing kinda gives identity away, when well trained), pets running around the place (useful to know who "did it again"), etc.: no luck.

Then I realized that this tool is specifically designed to handle face recognition.

## Question

1. Is this the right layer of abstraction where such support would be introduced?
2. Does the recognition of non-face objects depend on the backend engine, or is it configured by this tool?
3. Should I instead do the image recognition myself (incurring in the complexity of having to talk to/train the backend directly)?

**Comment by sstratoti** [comment]
I actually created my own deepstack model for USPS logos, and was using that in combination with a 2nd deepstack model for other package delivery logos.

https://github.com/sstratoti/DeepStack_USPS

https://github.com/OlafenwaMoses/DeepStack_OpenLogo

So if I were to spin up double-take and point it at these model's end-points, deepstack should return back any logos found that match the model. Would double-take care that they're not faces? Or does double-take specifically point at the v1/vision/face end-point?
