### ISSUE TITLE
[BUG] HTTP url for camera results in broken thumbnails

### ISSUE THREAD

**Issue by rsteckler** [jakowenko/double-take#156]
**Describe the bug**
I'm using the alternative latest and snapshot urls provided by this enhancement (which is awesome, by the way):  https://github.com/jakowenko/double-take/issues/110

When the match page is viewed, I get spinners for all thumbnails.  I figured out that the page is trying to load:
```http://doubletake.home:30080/api/storage/matches/2b6504b4-f8e8-4c4f-b56a-2d2a5e4b0c2f.jpg?thumb```

When I open that in the browser, I get:  
```
{"error":"VipsJpeg: Corrupt JPEG data: 608 extraneous bytes before marker 0xfe\nVipsJpeg: Corrupt JPEG data: 608 extraneous bytes before marker 0xfe\nVipsJpeg: out of order read at line 0\n"}
```

When I remove the thumb parameter, the full-size image loads correctly.

**Version of Double Take**
`v.1.6.0-893328f`

**Expected behavior**
Thumbnails should load

**Hardware**
 - OS: Ubuntu/Docker
 - Browser:  Chrome

**Comment by jakowenko** [comment]
Thanks for reporting this. Is this isolated to just the custom snapshot url thumbnails or is it across all images? I'm trying to figure out if the corrupt image data is originating from a single source to begin with or if it's also coming from Frigate images that are being saved.

**Comment by rsteckler** [comment]
This only happens on the custom snapshot URLs.  Frigate images load fine.

**Comment by jakowenko** [comment]
Would you be able to send me the raw image for one of them? Just want to use one to replicate this. At the very least I'll catch the error and return the raw image instead of it failing.

**Comment by jakowenko** [comment]
Hey @rsteckler, sorry for the delay. I just pushed up a new beta build that should fix this. I was able to test using your provided images as well.

Let me know how it looks on your end.

**Comment by rsteckler** [comment]
AMAZING!

Thanks so much for working through this one.  Always a pain when it's in an upstream lib.  Now I have Frigate operating from a low-res stream for object detection, then double-take grabbing a full-resolution frame for recognition.  I tested on one of my cams with low-res and high-res and it looks like recognition confidence is about 30 points higher at the distance I want to recognize faces.

Thanks!

**Comment by jakowenko** [comment]
Awesome! So glad it's working for you!
