### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wonkydog** [jakowenko/double-take#158]
**Describe the bug**
Maybe not a bug but a request for a little further info if I could both you?

In the docs I can specify a specific url under cameras and also frigate config?

Is there any difference? When would I use one over the other?

Also does this have any bearing on the required zones feature?

**Version of Double Take**
Latest

**Comment by jakowenko** [comment]
Hey sorry for the late response. The idea of the `cameras` object is to expose an API route to invoke the processing of a specific image. Typically you'd want to do this if you don't have Frigate, but have a URL to an image that is updated that you want to process via an API request.

If you are using Frigate, I would just set it up with the frigate settings.

Feel free to reopen if you have more questions.
