### ISSUE TITLE
[BUG] - If Uppercase letters are used Frigate camera names, duplicate cameras are created in Double Take

### ISSUE THREAD

**Issue by nmsousa76** [jakowenko/double-take#163]
**Describe the bug**
If Uppercase letters are used in Frigate camera names, duplicate cameras are created in Doubletake as well as Multiple Sensors in Home Assistant

Frigate Config
![image](https://user-images.githubusercontent.com/65356035/142056534-89c18168-123a-4019-bde1-6459a9b802c7.png)

Double Take

![image](https://user-images.githubusercontent.com/65356035/142056788-0223d5c7-9021-4dac-b124-cce3909b12c4.png)

Sensors 

![image](https://user-images.githubusercontent.com/65356035/142060241-d2f320b0-4ce2-430a-a5ac-4e2ab7129f05.png)

**Version of Double Take**
1.6.0

**Expected behavior**

Remove case sensitivity from camera automatically created in Doubletake.   This will prevent duplicate sensors from being created in home assistant
 
**Screenshots**
See inline above

**Hardware**
 HASS running on a Intel Nuc

**Additional context**
I was able to solve (or at least work around) the issue, by by setting mqtt to false in the doubletake config, or by putting all my cameras to lower case in the frigate config

**Comment by jakowenko** [comment]
@nmsousa76 this should be fixed now in the beta build. The camera names used in the topics will be lowercase. Let me know if it works for you.

**Comment by jakowenko** [comment]
This was fixed in the latest release `v1.7.0`. If you encounter any other issues feel free to reopen to make a new issue.
