### ISSUE TITLE
[FEAT] Allow for custom URL path

### ISSUE THREAD

**Issue by dannytech** [jakowenko/double-take#166]
**Is your feature request related to a problem? Please describe.**

It would be very useful to be able to change the URL path of Double Take so it can run alongside other applications. In my setup, I'm using Nginx to proxy to both Frigate (at `/`) and Double Take (at `/double-take`), but the issue is that putting DT in its own location block like below doesn't work.

```nginx
location /double-take/ {
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;

    proxy_pass http://ip6-localhost:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

The page doesn't properly load, since DT assumes that it is being accessed at just `/`. The CSS and JS loads properly (since it uses relative paths), but then requests made to `/api/...` fail since the correct path would be `/double-take/api/`.

![image](https://user-images.githubusercontent.com/20747523/142673741-e35b08f5-757b-41f1-b490-0c6fc05ad5f1.png)

The URL bar also changes to just `/login`. The resulting page looks like this (note that I do not have authentication turned on in my config):

![image](https://user-images.githubusercontent.com/20747523/142673011-6ef3af9a-3023-4192-94fd-21084f829824.png)

**Describe the solution you'd like**

Ideally, it would be possible to specify the path that Double Take will be available at, for example with the following in the config file:

```yml
ui:
  path: /double-take
```

If there is another solution/workaround please let me know.

**Comment by jakowenko** [comment]
Hey @dannytech, I pushed a new beta build that should include a config option just like you suggested. I use traefik as my reverse proxy and was able to test everything under local.domain.com/double-take

Let me know if it works for you.

```yaml
ui:
  path: /double-take
```

**Comment by dannytech** [comment]
Thanks, works great with my setup! Had to make sure Nginx requests `/double-take/` from the backend, which might be good to document (since some setups simply change the path on the frontend but still serve internally from `/` which the proxy then rewrites).

```nginx
location /double-take/ {
    proxy_pass http://ip6-localhost:3000/double-take/;
}
```
