### ISSUE TITLE
[FEAT] Ability to Delete and Readd Users

### ISSUE THREAD

**Issue by LordNex** [jakowenko/double-take#179]
This would be a partial workaround hopefully for the user's sensors not populating in Home Assistant. If we had the option to delete a user. then readd them and retrain so that it would see them as a new user and upon the first detection, should create the proper sensor. My son's sensor won't show up and he's one of the main people who will be using this so I thought it would be a good feature to add. Currently you can untrain images, but the user is still there and all you can do is retrain images for the user again or create a new person with a different name which just isnt practical. Let me know if there is anything I can do to help! And kick as work man!!!

**Comment by LordNex** [comment]
Figured I’d add this question here instead of creating a new issue but if you think it should have a separate feature request, just let me know and I’ll make one. 

I need to be able to untrain an image from a person. Obviously from time to time an image that isn’t who it should be gets accidentally trained. Just happened to me where I clicked on the wrong picture while selecting a bunch in the list of matches to be trained. If I foot the train section my only option is to untrain all images, which would be fine if I could then remove the offending image, but it doesn’t look like I can do that. Anyway, thanks again as always and have a very Merry Holidays!

**Comment by jakowenko** [comment]
Hey @LordNex, thanks for the detailed request and happy holidays! Also thank you for checking out and using Double Take, it really means a lot!

I believe there should be a way to accomplish what you are looking for, maybe the UI is just a bit confusing.

If you untrain all the images for a current user, you can then delete the user. The button should turn from "untrain" to "remove".

<img width="459" alt="CleanShot 2021-12-26 at 22 32 52@2x" src="https://user-images.githubusercontent.com/1081811/147431682-83c59571-07b1-4052-9eb7-adbb5f06dba9.png">

Also, for a sensor to show up, a successful match needs to occur. Is there a chance there just hasn't been a match of your son yet within Double Take?

For your second question, you should be able to untrain a single, multiple, or all images for a user.

If you select images and then use the trash button on the right hand side, you can untrain/delete just those images.

<img width="202" alt="CleanShot 2021-12-26 at 22 35 33@2x" src="https://user-images.githubusercontent.com/1081811/147431826-25e4ea2b-01d5-47e6-9ccf-a25c2e7f359e.png">

Let me know if that makes sense and will solve the issues you were having.

**Comment by LordNex** [comment]
> 

Thanks for getting back to me so fast. I hope you had a wonderful Christmas Holiday.

His sensor finally did show up. I had to reboot everything and get things just right so I knew it would do a proper recognition, and then it showed up. 

And as far as removing a user and retraining images. That was exactly what I was looking for. Just never thought to untrain the images first. A little blurb in the help dock might be helpful to others.

The only issue I have left is related to how Double take connects to DeepStack, But there is an already open ticket from someone else that I've been commenting on and I'll update that as I have new info. Again, very cool and badass programming skills man. I've been in IT for over 20 years and have just now really started to get into programming. But while going down the rabbit hole that I was bound and determined to have my house recognize me and my family, let us in, and greet us like on Back to the Future 2 or something. I would have had to hack together IFTTT with a ton of automation and scripts to get what you've so elegantly accomplished. When I can I plan on throwing a few dollars your way as its well worth it.

I've leave this for you to close if you wish or use to update other people on. Thanks again!

**Comment by jakowenko** [comment]
Sorry for the delay. Thank you for all the compliments. If you run into any issues in the future or have other ideas feel free to open a new request.
