### ISSUE TITLE
use snapshot image from the mqqt message instead of fetching from the api

### ISSUE THREAD

**Issue by erikarenhill** [jakowenko/double-take#18]
Currently the snapshot is fetched from frigate by posting to 0.0.0.0:PORT/recognize from the mqtt client, but since frigate publishes the snapshots binary image with the mqtt message maybe we could get better performance by just using the data that we already got with the message?

Or are there any other reasons why to fetch the image again with axios, maybe I'm missing something.

**Comment by erikarenhill** [comment]
this would require to fetch FRIGATE/api/config to see which cameras that's available at start/some polling interval, and then subscribe to the frigate/{CAMERA}/person event which is the event which contains the snapshot data

**Comment by jakowenko** [comment]
Hey @erikarenhill, I got this into the latest beta build. Let me know what you think. You can configure the Frigate snapshot MQTT image as well, the default is pretty small.

https://blakeblackshear.github.io/frigate/configuration/cameras/#full-example

**Comment by Raphael909** [comment]
Hey @jakowenko , I was wondering what are your thoughts or plan to get this feature into master branch or cut a new release.
Thank you for this fantastic software!

**Comment by jakowenko** [comment]
Hey @Raphael909, thank you for the compliments. I just published [v0.6.0](https://github.com/jakowenko/double-take/releases/tag/v0.6.0) which has this feature along with a few other changes. If you have any other feedback for feature suggestions feel free to open up a new ticket.
