### ISSUE TITLE
[BUG] Zones not working as intended

### ISSUE THREAD

**Issue by 0xPDG** [jakowenko/double-take#182]
**Describe the bug**
I have setup a zone in Frigate and Double take but am still getting analysis on the camera outside said zone.
Zone seems works fine as I do get events in Double take tagged as coming from the zone.

**Version of Double Take**
`1.7.0-bf3e911`

**Expected behavior**
For facial detection to happen only for events in the zone as said in the documentation.

**Screenshots**
https://imgur.com/a/5AZO9QC
Double take config extract on top, frigate zone config on bottom.

**Hardware**
 - Home Assistant Supervised core-2021.12.3 running on Buster

**Comment by jakowenko** [comment]
@PGaujac, do you happen to know if the event that Double Take produced a match on did enter the Frigate zone originally?

Double Take just checks the Frigate message to see if it includes a zone before the detection occurs. So there could be a person who walks in X zone, which triggers Double Take, but then walks out of the zone, but Double Take is still processing the images and then finds a match when the person has left the zone. There isn't any logic done to determine if the person is in the zone, only that the Frigate message includes it.

One thing you could try is to configure [masks](https://github.com/jakowenko/double-take#cameras) in Double Take for everything around the zone. That way the mask is applied before sending the image for recognition, which would make it impossible to produce a match if it's outside of zone.

**Comment by PGaujac** [comment]
Hello, sorry for the late reply, I returned my cameras and had to wait for the new ones to arrive to do further testing.

It's happening way out of the zone and with events that don't come close to it.

I will try the mask solution in the mean time.

**Comment by PGaujac** [comment]
Hello, turns out zones were kind of working.
All the events that were getting processed were coming to double take via mqqt, I was not getting any events from snapshots outside of the set zone.

Setting mqqt: false in the attemps section of double take config solves this behavior and I now only get processing where I want.

Is this by design or an oversight/bug ?

**Comment by jakowenko** [comment]
Sorry for the delay. The processing of Frigate events and snapshots are two separate processes. When the `frigate/<camera-name>/person/snapshot` topic is updated, there is no context around the event. Setting `mqtt: false` like you mentioned is a solution for this.

The other Frigate MQTT events come with zone data. I will update the docs to make note of this so it's more clear.
