### ISSUE TITLE
[BUG] Notification with image - I didn't succeed to get image from the external link [HA]

### ISSUE THREAD

**Issue by antonbek89** [jakowenko/double-take#187]
Hi
I have an issue with HA and notification image
I didn't succeed to get image from the external link
If I going browse from a device which not authorized to 

`https://abc.duckdns.org:8123/media/local/double-take/matches/17eab047-d81e-4cc2-8fb0-dda85b6821c7.jpg?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1NjYyNjEzZmFmYWI0YmUxOTMzMzYxOThkMzI4MDU5MSIsInBhdGgiOiIvbWVkaWEvbG9jYWwvZG91YmxlLXRha2UvbWF0Y2hlcy8xN2VhYjA0Ny1kODFlLTRjYzItOGZiMC1kZGE4NWIwNzQwYzcuanBnIiwiaWF0IjoxNjQyNDU3MzU3LCJleHAiOjE2NDI1NDM3NTd9.lbLSaCjUQ4cVykVQbVnq49NkBI0nvKHfS9_BGUFLtdU`

I can see the snapshot.

The problem is with the **authSig** token - he always changes

When I tried browsing to snapshot via Double-take link and not authorized device

`https://abc.duckdns.org:8123/api/hassio_ingress/wxZONpw2YVgYS7hH32s_Bs-8nalnsaKXI77rr2QEou8/api/storage/matches/1533255c-8ef6-4459-b43d-83a43e16b1bc.jpg?box=true`

I got **401: Unauthorized**

My domain - https://abc.duckdns.org:8123

My automation

```
      data:
        image: "{% if trigger.to_state.attributes.match is defined %}\n https://abc.duckdns.org:8123/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% elif trigger.to_state.attributes.unknown is defined %}\n https://abc.duckdns.org:8123/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}\n\
          {% endif %}"
```

How do I solve this problem?

**Comment by SgtBatten** [comment]
I'm also looking to understand how to access the images remotely. The example notification script uses localhost which obviously doesn't work on any other device.  I only have home assistant reverse proxied, not double take or frigate. frigate seems to provide an external access using my home assistant domain but i have not worked out if double take does or can.

**Comment by jakowenko** [comment]
> I'm also looking to understand how to access the images remotely. The example notification script uses localhost which obviously doesn't work on any other device. I only have home assistant reverse proxied, not double take or frigate. frigate seems to provide an external access using my home assistant domain but i have not worked out if double take does or can.

I run mine behind a reverse proxy. If you aren't using `auth` within Double Take, then you would just access images via the API the same way as `localhost`. You would just replace it with what domain you are running behind.

If you have `auth` enabled, you can create a token within the UI and append this static value to make the images render with the auth.

<img width="500" alt="2022-05-25 at 00 22 54@2x" src="https://user-images.githubusercontent.com/1081811/170179277-2fab4a33-5376-4d9b-950c-ced27381d4b5.png">

Feel free to reopen if either of you are still having issues.

**Comment by LordNex** [comment]
> > I'm also looking to understand how to access the images remotely. The example notification script uses localhost which obviously doesn't work on any other device. I only have home assistant reverse proxied, not double take or frigate. frigate seems to provide an external access using my home assistant domain but i have not worked out if double take does or can.
> 
> 
> 
> I run mine behind a reverse proxy. If you aren't using `auth` within Double Take, then you would just access images via the API the same way as `localhost`. You would just replace it with what domain you are running behind.
> 
> 
> 
> If you have `auth` enabled, you can create a token within the UI and append this static value to make the images render with the auth.
> 
> 
> 
> <img width="500" alt="2022-05-25 at 00 22 54@2x" src="https://user-images.githubusercontent.com/1081811/170179277-2fab4a33-5376-4d9b-950c-ced27381d4b5.png">
> 
> 
> 
> Feel free to reopen if either of you are still having issues.

- [ ] Question, according to the notification script you have as an example appears to pull the notification from a state variable. I still receive an Unauthorized page when clicking the link although the thumbnail appears fine from the push notification. Do re remove that variable from the template and put the access token in there statically or is there another place to define that variable?

```

        actions:
          - action: URI
            title: View Image
            uri: |-
              {% if trigger.to_state.attributes.match is defined %}
                http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}
              {% elif trigger.to_state.attributes.unknown is defined %}
                 http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}
              {% endif %}
```
