### ISSUE TITLE
Frigate only snapshots with person box result in a large enough face box

### ISSUE THREAD

**Issue by steppel** [jakowenko/double-take#193]
So, I'm still trying to wrap my head around the correct frigate/double take settings. My observation is the following. When double take gets snapshots with person box from frigate it's able to have a large enough face box. All other snapshots without person box seem to always result in too small face box. Is there anything I can set to only get those snapshots with person box? 

Also, see attached screenshot, why is it recognizing my hand with a match:true 🤔

![image](https://user-images.githubusercontent.com/49464956/155256310-e9fac72f-bc0c-4d20-8c72-bbc23753fcfd.jpeg)

**Comment by NickM-27** [comment]
Can you show an example of one that is too small? Odds are those are the MQTT images which have different size config in frigate and by default are too small / not high quality enough (they are also cropped by default).

Also as far as the hand goes, compreface does what compreface does and it saw a face there.

**Comment by srvoets** [comment]
I dont want to create a new topic for this, so I am going to piggy-back


Is there a config settings somewhere, that I am missing that will only attemot to "detect" if the face box is a certain size?

I have LOTS of 'unknowns' and incorrect matches when the person is still 15-20ft away from my front door.

I tried setting up a zone in frigate to monitor, but Im afraid the camera angle of the ad110 means using zone notifications is less effective

**Comment by NickM-27** [comment]
> I dont want to create a new topic for this, so I am going to piggy-back
> 
> Is there a config settings somewhere, that I am missing that will only attemot to "detect" if the face box is a certain size?
> 
> I have LOTS of 'unknowns' and incorrect matches when the person is still 15-20ft away from my front door.
> 
> I tried setting up a zone in frigate to monitor, but Im afraid the camera angle of the ad110 means using zone notifications is less effective

Yes, it is here:

```yaml
 unknown:
    # minimum area in pixels to keep an unknown result
    min_area: 0
```

**Comment by jakowenko** [comment]
Thanks @NickM-27 for helping on these. Going to close for now as I believe all of these can be addressed with config options as mentioned above. Most of them are listed [here](https://github.com/jakowenko/double-take#detect).

@steppel in the case of your original image, I don't believe your hand was considered to be a match. But the detector did say it was 59%. Since the number is red it means it didn't meet the threshold for it to be a match.
