### ISSUE TITLE
[BUG] compreface mobilenet + config tab = cpu out for few minutes

### ISSUE THREAD

**Issue by luzik** [jakowenko/double-take#197]
While using compreface configured to use InsightFace backend with cpu only support, every time I open double-take config tab, my modern cpu is out for few minutes. Training and daily face recognition works smooth (much less false positives that default facenet backend), only that config tab make it hang.
Is it related to compreface availability checking from that tab ?

**Comment by luzik** [comment]
This can be related to
https://github.com/jakowenko/double-take/pull/185/commits/490ce4300b323c331d69c9b5774277f2a4f41904

**Comment by jakowenko** [comment]
Sorry for the delay. The commit in question has now been merged in. Please open a new issue if the problem persists.
