### ISSUE TITLE
Setting retention period

### ISSUE THREAD

**Issue by russellevans** [jakowenko/double-take#200]
First can I say that Double Take is totally awesome.
Next my experience is low and the following may be daft questions due to my a lack of knowledge..

I cannot find a way to set a retention period for the matching images.  My concern that if left unchecked it will fill up the drive and lead to issues.

Also is there an option to set where the image are saved too such a network folder.

I have found the setting in Frigate for both retention period and setting network

My setup is...

1.   Main host machine Dell power edge T430 with Proxmox hypervisor
2.   3.   Home Assistant running in VM on T430
4.   Frigate as Home assistant add on 
5.   Deepstack running on Jetson Nano
6.   True NAS running in VM on T430

**Comment by NickM-27** [comment]
It's here in the readme:

detect:
  match:
    # hours to keep match images until they are deleted
    purge: 168

  unknown:
    # hours to keep unknown images until they are deleted
    purge: 8

**Comment by russellevans** [comment]
Thanks for coming back so quickly. 

All sorted now
