### ISSUE TITLE
Double take unable to connect to Frigate

### ISSUE THREAD

**Issue by tgooro** [jakowenko/double-take#202]
I am running double take in a docker outside of HA and Frigate. I have Frigate setup on a separate docker and HA setup on an Odroid+. I have setup deepstack and Compreface in separate dockers. When adding configuration, I am able to connect to MQTT, Compreface and Deepstack but double take is not able to connect to Frigate. Below is the log of when double take starts:

info: Double Take v1.7.0-bf3e911
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
error: Error: connect EHOSTUNREACH 192.168.10.30:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
error: Error: connect EHOSTUNREACH 192.168.10.30:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
error: Error: connect EHOSTUNREACH 192.168.10.30:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
error: Error: connect EHOSTUNREACH 192.168.10.30:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
error: Error: connect EHOSTUNREACH 192.168.10.30:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)

192.168.10.30 is the ip of Frigate.

**Comment by NickM-27** [comment]
What are the IPs of the other services like MQTT?

**Comment by jakowenko** [comment]
@tgooro did you get this resolved? I'm going to close for now, but feel free to reopen if you're still having issues.
