### ISSUE TITLE
No files found

### ISSUE THREAD

**Issue by MRobi1** [jakowenko/double-take#205]
**Describe the bug**
All I'm seeing within double-take is "No files found"

In the double-take logs I see it processing the images
```
22-04-30 16:34:17 info: processing side_doorbell: 3b02eebb-fb15-47d7-900d-59dd1f326de6
22-04-30 16:34:17 info: done processing side_doorbell: 3b02eebb-fb15-47d7-900d-59dd1f326de6 in 0.22 sec
22-04-30 16:34:17 info: {
  id: '3b02eebb-fb15-47d7-900d-59dd1f326de6',
  duration: 0.22,
  timestamp: '2022-04-30T16:34:17.431Z',
  attempts: 1,
  camera: 'side_doorbell',
  zones: [],
  matches: [],
  misses: []
}
```
Also seeing lots of activity in deepstack logs
[GIN] 2022/04/30 - 16:34:10 | 200 |  245.068095ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |  247.202432ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |  256.210077ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |  107.555009ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |   98.794998ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |   65.469808ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |    70.75116ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:10 | 200 |   60.752443ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:11 | 200 |   58.142777ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:11 | 200 |   86.751317ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:11 | 200 |   98.243648ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:11 | 200 |   62.523221ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:17 | 200 |  209.326623ms |      172.XX.XX.XX | POST     "/v1/vision/face/recognize"
[GIN] 2022/04/30 - 16:34:17 | 200 |  200.978954ms |    192.XX.XX.XX | POST     "/v1/vision/face/recognize"

**Version of Double Take**
v1.7.0-bfe3911:latest

**Expected behavior**
Images to appear in double-take

**Screenshots**
![Capture](https://user-images.githubusercontent.com/34860474/166114906-afc33451-8f21-4df7-9a15-e3a427bcb976.PNG)

**Hardware**
 - Ubuntu LXC, docker

**Additional context**
Just working at setting this up today. Not really sure where to start troubleshooting. Frigate is sending the snapshots, it appears that both double-take and deepstack are seeing them, but nothing appears anywhere. I've uploaded a few images into the "Train" section but still nothing shows up under matches, either known or unknown. Where should I start troubleshooting?

**Comment by NickM-27** [comment]
What's your config look like? Entirely possible that your settings for unknown are causing it to not show those. The logs also seem to indicate that deepstack saw no matches or potential matches

**Comment by MRobi1** [comment]
Ultimately I ended up trying compreface as a detector and everything just worked, so I've left it at that and it's been running just fine ever since.
