### ISSUE TITLE
[BUG?] How to upgrade Home Assistant addon

### ISSUE THREAD

**Issue by Calimerorulez** [jakowenko/double-take#210]
I saw that DoubleTake v 1.9.0 is available, but my Home Assistant add-on still says 1.7.0. I've manually checked for updates, but none are available.

The description of the addon does say 1.9.0:

![image](https://user-images.githubusercontent.com/1130552/169843877-9019a1ea-ecf4-4af3-835a-6d0d7347defb.png)

Can somebody advise? Thanks :)

**Comment by jakowenko** [comment]
v1.9.0 should be available as an update now.

![2022-05-23 at 14 29 38](https://user-images.githubusercontent.com/1081811/169884349-e552c7bb-716c-4800-b710-95cafd59fdd5.png)

**Comment by Calimerorulez** [comment]
Updated ok, thank you!
