### ISSUE TITLE
[Behavior Request] Sort Names When Submitting as Sub Labels

### ISSUE THREAD

**Issue by NickM-27** [jakowenko/double-take#217]
**Describe the bug**
Not really a bug, but I have seen a couple multiple-name submissions for frigate sub labels and they appear in chronological order but I think it would be better if they were alphabetized. We are adding a filter and otherwise `John, Bob` `Bob, John` appear as separate entries which can add clutter. I don't think it makes as much sense for frigate to handle this but I am open to that if it makes more sense for frigate to check for comma separated names.

**Comment by jakowenko** [comment]
I'll take care of this on the Double Take side. It's easy enough to sort before pushing to Frigate.

**Comment by jakowenko** [comment]
@NickM-27 have you had a chance to try out the beta build? It should include this.

**Comment by NickM-27** [comment]
I've been running it but haven't had an opportunity to test multiple people at the same time. That being said, I don't see how this wouldn't be working as expected

**Comment by jakowenko** [comment]
This was merged into master and included in the latest release. Let me know if you run into any issues.
