### ISSUE TITLE
[FEAT] Add Total Count for Matches, Misses and Unknown To MQTT Payload 

### ISSUE THREAD

**Issue by DevTodd** [jakowenko/double-take#223]
**Describe the solution you'd like**

For the MQTT Payload published to sensor/double-take/*camera name*/state it would be nice to get 

matchCount
missCount 
unknownCount

in addition to the already present 

personCount

Thanks!

**Comment by jakowenko** [comment]
Hey @DevTodd, sorry for the delay in responding to this. I should have a new beta build with this added within the next day or two. I refactored a bit during the process so it took a little longer than I wanted.

Thank you for the suggestion and the sponsorship. It really means a lot to me!

**Comment by jakowenko** [comment]
I pushed a beta build to include this feature. I removed the `personCount` in favor of grouping all of the new values in an object called `counts`. I also tweaked how the counts are calculated to hopefully make it a bit more accurate.

Let me know what you think!

```json
{
  "id": "ff894ff3-2215-4cea-befa-43fe00898b65",
  "duration": 4.25,
  "timestamp": "2021-06-17T03:19:55.695Z",
  "attempts": 5,
  "camera": "back-door",
  "zones": [],
  "matches": [
    {
      "name": "david",
      "confidence": 100,
      "match": true,
      "box": { "top": 286, "left": 744, "width": 319, "height": 397 },
      "type": "manual",
      "duration": 0.8,
      "detector": "compreface",
      "filename": "dcb772de-d8e8-4074-9bce-15dbba5955c5.jpg",
      "base64": null
    }
  ],
  "misses": [],
  "unknowns": [],
  "counts": { "person": 1, "match": 1, "miss": 0, "unknown": 0 }
}
```

**Comment by DevTodd** [comment]
Thank you for taking the time to do this.  It breaks a lot of my automations since I was previously using personCount as it was the only option available that I could use to determine if more than one person was detected.  

I'm working 18 hour days lately due to some new secops regulations so when I have time I will test.  Again, thank you for the work and consideration of my request.

**Comment by jakowenko** [comment]
I will add it back for now as backwards compatibility and make a note that I will remove it in a future release. I don't want to break any of your automations.

No rush on testing, sorry to hear about the long days at work! I've been using it over the past day around the house and it seems to be working well, I will probably create a release tonight.

Feel free to message me on Discord if you run into any issues and I'll get it fixed right away.

**Comment by jakowenko** [comment]
Closing this since `v1.13.0` has been released! Let me know if you run into any issues.
