### ISSUE TITLE
Double-take says a face is a trained entity every time.

### ISSUE THREAD

**Issue by gatorreina** [jakowenko/double-take#227]
Perhaps my config below is wrong but I cannot get double-take to classify a face as unknown or a miss. No matter what it classifies a face as one of my trained entities. I have even tried setting the confidence rate to 99% however it nevertheless gives the name of one of my trained entities for any face presented even if the confidence level is below well below 99%. 

I am running double-take with compreface as the detector in docker compose:
double-take:
    container_name: double-take
    image: jakowenko/double-take

**Expected behavior**
For double-take to say face is "unknown" if the confidence level is below that which is set, in my case 99%.

**Hardware**
 - OS: Debian
 - Browser Chrome, Safari

**Additional context**
My Config file:

mqtt:
  host: minisforum1
  port: 1883
  
  topics:
    # mqtt topic for frigate message subscription
    #frigate: frigate/events
    #  mqtt topic for home assistant discovery subscription
    #homeassistant: homeassistant
    # mqtt topic where matches are published by name
    matches: double-take/matches
    # mqtt topic where matches are published by camera name
    #cameras: double-take/cameras

home_assistant:
  url: http://beelink1:8123

frigate:
  url: http://beelink1:5000

detectors:
  compreface:
    url: http://beelink1:8000
    key: 00000000-0000-0000-0000-000000000002
    det_prob_threshold: 0.99

detect:
  match:
    confidence: 99
  unknown:
    # save unknown images
    save: true
    confidence: 40

**Comment by jakowenko** [comment]
Can you send me a screenshot of what your matches page looks like so I can see how the results are coming back? If the name is in red, then it means it's not considered a match. I have my unknown.confidence value at 70. Which means any value under 70% will be renamed to `unknown`

```yaml
detect:
  match:
    confidence: 90
  unknown:
    confidence: 70
 ```

**Comment by jakowenko** [comment]
Sounds great, let me know if it works.

Increasing the `confidence.unknown` value to a higher one will change the name to unknown.

**Comment by gatorreina** [comment]
Upping the confidence level for unknown so that anything below that percentage is marked unknown was the key. Thank you. Issue is solved. Much appreciated and thank you for creating Double-take.
