### ISSUE TITLE
[BUG] Error in Notification Automation

### ISSUE THREAD

**Issue by LordNex** [jakowenko/double-take#230]
**Describe the bug**

There is a bug in the notification automation you have listed in the read me section

Executed: July 23, 2022, 10:53:48 AM
Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'to_state'

**Version of Double Take**
`1.12.1`

**Expected behavior**

Notification to fire off

**Screenshots**

![image](https://user-images.githubusercontent.com/9270948/180612918-c026128b-fea0-4480-baf9-c447da4dade2.png)

**Hardware**
 - OS: Home Assistant OS running in a 40 core 256gig Dell PowerEdge R620 running VMWare ESXi 7 and Home Assistant in a guest VM[e.g. Ubuntu, macOS, Windows]
 - Browser (if applicable) [e.g. Chrome, Safari] Home Assistant App or any browser

**Additional context**

**Comment by LordNex** [comment]
I'm going to close this. It took some work but I finally figured out the proper templates to get this to work. Well hopefully, haven't fully tested. But I'm pretty sure. LOL

**Comment by ninjasstudio** [comment]
did you end up figuring this out? i have the same issue
