### ISSUE TITLE
Double-Take not creating Sensor for trained PICs[BUG]

### ISSUE THREAD

**Issue by dhtguru** [jakowenko/double-take#233]
**Describe the bug**
Successfully trained several pictures to names, but the names are not showing up as sensors (sensor.double_take_myname).  

**Expected behavior**
HA displays the names I have selected to train as sensors.

**Screenshots**

**Hardware**
 - OS: Debian 11
 - Browser: Brave

**Additional context**
I have the unknown, front door, driveway, and update sensors, but not the sensors with the persons name.  Otherwise, everything else is working perfectly.

**Comment by NickM-27** [comment]
The sensors are based on MQTT so they won't be created until doubletake sends a match for that topic, once there is a match it will be created. This is the expected behavior.

**Comment by dhtguru** [comment]
Thanks
