### ISSUE TITLE
Double take doesn't connect to Frigate

### ISSUE THREAD

**Issue by verschup76** [jakowenko/double-take#237]
I have installed the double-take addon in HA, and the 'lights' are all green, indicating that it's connected to deepstack and frigate.

However, I can't select any filters, see any matches come through and my log file tells me it cannot connect to Frigate:
22-08-31 17:30:41 error: Error: frigate status error: connect ECONNREFUSED 192.168.1.xxx:5000
    at Object.module.exports.checks (/double-take/api/src/util/frigate.util.js:74:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:85:21)

The IP address for Frigate is correct,

mqtt:
  host: 192.168.1.xxx
  username: mqqt
  password: password1234

frigate:
  url: https://192.168.1.xxx:5000

detectors:
  deepstack:
    url: http://192.168.1.xxx:80
    key: xxxxx
    timeout: 3000

Any help would be greatly appreciated.

Kr,

Pim

**Comment by hugalafutro** [comment]
Is the protocol for frigate host correct too? I just set up a double-take stack and it works out-of-the box with frigate running on http:// address so the only difference in your case would be frigate running on https://

**Comment by verschup76** [comment]
Hi,

I was using the 80 port for deepstack, and since I have changed that to the 5001 port it works perfectly.

Not sure why the installation guide says 80, but it wasn't working for me.

Thanks for your comment though.

Pim

**Comment by verschup76** [comment]
Ok, got a bit closer to what's causing my issues. I was running Frigate and deepstack from the same machine. It seems like deepstack needs to run from port 5000 (a bit weird) as I need to be able to get to the activation page. I haven't seen this mentioned anywhere, but if I can't get to this page, it just doesn't work. So at the moment I have Deepstack and Frigate running on different machines, but any help on how I can get around this and run it on one machine would be greatly appreciated.
 
On another note, I only seem to be able to detect faces in double take and I can't figure out why.

Thanks,

Pim

![image](https://user-images.githubusercontent.com/26470786/189235226-705a17fe-99e7-4aaf-a9ce-90c46ab9b738.png)

**Comment by csw3190** [comment]
@verschup76 try changing Frigate to another port (eg 5002). For some reason, 5000 wasn't working for me and 5002 via http works just fine.

**Comment by verschup76** [comment]
Had to look a bit but finally found where I could change the port. I guess it was a bit too obvious. Thanks!!
