### ISSUE TITLE
Support latest version of compreface

### ISSUE THREAD

**Issue by eyalcha** [jakowenko/double-take#238]
https://github.com/exadel-inc/CompreFace/blob/master/.env

Note that although the env has version 1.1.0, the actual images in docker hub are 1.0.1

**Comment by jakowenko** [comment]
I bumped the addon to [CompreFace v1.1.0](https://github.com/jakowenko/double-take-hassio-addons/commit/ae86b62111aa46cf5dd1dcb9c7ed5a9d181f395c), let me know if you run into any issues.
