### ISSUE TITLE
save_unknown also saves images with high confidence

### ISSUE THREAD

**Issue by erikarenhill** [jakowenko/double-take#25]
maybe there should be 2 env vars, one save_unknown and one save_all_faces or something,
right now save_unknown also includes matches with 90% confidence to the train/manage gui even though I have that setting to about 70-75

**Comment by jakowenko** [comment]
I'm not sure I understand. Right now any time a face is found from the detector but the confidence is less than the specified one it's considered unknown. When the all the detection attempts are done, these unknown images along with the matches are saved out.

**Comment by erikarenhill** [comment]
> I'm not sure I understand. Right now any time a face is found from the detector but the confidence is less than the specified one it's considered unknown. When the all the detection attempts are done, these unknown images along with the matches are saved out.

Hi, what I meant was that the training/manage gui should filter (with my personal preference) out those with a confidence higher than configured if not a specific environment variable is set.

An option would be to have a checkbox in the web page such as "show all" or "only show unknown" to reduce the amount of pictures when managing, where you might not want to handle those with a high confidence. Or a drop-down with 5% increments that you can select for example show those under 70%, 75%, 80%, etc

**Comment by jakowenko** [comment]
@erikarenhill what do you think of a filter menu like this? It would give the user quite a few ways to narrow down the matches. Is there anything else you think would be useful?

![Screen Shot 2021-04-15 at 2 35 44 AM](https://user-images.githubusercontent.com/1081811/114824981-a3469f80-9d93-11eb-8d60-019d48a87aa3.png)

**Comment by erikarenhill** [comment]
@jakowenko that looks awesome. No more ideas on queue right now! :)

**Comment by jakowenko** [comment]
Awesome, glad you like it. Feel free to open up a new issue if you have any other ideas around this. Closing this one for now. Hoping to merge all this into master within the next week or so.
