### ISSUE TITLE
Can I use double take with an ip camera without using frigate?

### ISSUE THREAD

**Issue by Doublefire-Chen** [jakowenko/double-take#255]
**Is your feature request related to a problem? Please describe.**
Frigate costs too much cpu usage of my NAS, I don't want to use frigate.

**Describe the solution you'd like**
Maybe a NVR with less cpu costs can be alternative.

**Comment by Doublefire-Chen** [comment]
I know how to solve this. I can use the upload api to replace the frigate. I just need to write an automatic upload program using python.

**Comment by HopePAPA** [comment]
Hello, this need how to do?Can you teach me？
