### ISSUE TITLE
[BUG] error: config requires property "detectors"

### ISSUE THREAD

**Issue by chench00** [jakowenko/double-take#286]
**Describe the bug**
I tried to upgrade from the beta to the latest and now receive the error above. 

**Version of Double Take**
`Double Take v1.13.1-8e2728d`

**Expected behavior**
Start

**Screenshots**

**Hardware**
 - OS: Ubuntu 20.04
 - Browser (if applicable) [e.g. Chrome, Safari]

**Additional context**

        mqtt:
          host: 192.168.141.21

        home_assistant:
          url: http://192.168.141.11:8123
          token: TOKEN

        frigate:
          url: http://192.168.141.21:5000

        detectors:
          compreface:
            url: http://192.168.143.11:8000
            key: KEY

------

        services:
          double-take:
            container_name: double-take
            image: jakowenko/double-take
            restart: unless-stopped
            volumes:
              - ${PWD}/double-take/.storage:/.storage
            ports:
              - 3000:3000

**Comment by chench00** [comment]
Resolved.

**Comment by townsmcp** [comment]
@chench00 how did you resolve this?

**Comment by chench00** [comment]
Honestly, I believe it was due to a misconfiguration on my part but I don't recall exactly. It could have been that I added the `go2rtc` part to the wrong section of my configuration. 

Sorry for the delay in replying.
