### ISSUE TITLE
[BUG] Double-take cannot be setup to detect faces smaller than 100x100

### ISSUE THREAD

**Issue by heisenberg2980** [jakowenko/double-take#326]
**Describe the bug**
Setting min_area_match in the config doesn´t seem to do anything as double-take is still comparing the size of the image with 10000 instead of the value of min_area_match

**Version of Double Take**
v1.13.1

**Expected behavior**
Changing min_area_match to 5000 should mark any image above 5000 pixels as a match

**Screenshots**
![image](https://github.com/jakowenko/double-take/assets/58039006/e8399c10-0f78-4b44-a788-75f364c170d4)

**Hardware**
 - OS: Docker running in Proxmox
 - Browser (if applicable): Chrome

**Additional context**
My config:
```
# Double Take
# Learn more at https://github.com/jakowenko/double-take/#configuration
# enable authentication for ui and api (default: shown below)
auth: true

mqtt:
  host: 192.168.0.253
  username: !secret mqtt_user
  password: !secret mqtt_pass

objects:
  face:
    min_area_match: 5000
  
frigate:
  url: http://192.168.0.209:5000
  # if double take should send matches back to frigate as a sub label
  # NOTE: requires frigate 0.11.0+
  update_sub_labels: true
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 0
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 1
  
detectors:
  compreface:
    url: http://192.168.0.209:6001
    # recognition api key
    key: !secret compreface_key
```

**Comment by heisenberg2980** [comment]
This issue makes double-take unusable for me as all my cameras detect faces smaller than 100x100, is nobody else having this issue?

**Comment by timknowlden** [comment]
Yes @heisenberg2980 all of my detections are under 100x100 of which it can't match.. dont know if its a frigate or doubletake config issue?

**Comment by DieMetRik** [comment]
Wrong section of min_area

detect:
  match:
    # minimum area in pixels to consider a result a match
    min_area: 13000

**Comment by timknowlden** [comment]
> Wrong section of min_area
> 
> detect: match: # minimum area in pixels to consider a result a match min_area: 13000

Thanks, however i fear that decreasing the box area may result in more detection errors, i would like to send a larger image of the face when captured by frigate? crop around the person box for example (removing the rest of the image that isnt a person) and send that image?

**Comment by heisenberg2980** [comment]
@timknowlden the size of the face is dependant on the resolution of the image captured by Frigate. If you have setup frigate to use the maximum resolution your camera provides then you are out of luck, but if your camera has a higher resolution then you have to setup frigate to use a higher resolution so the faces recognized will also have a higher resolution.

**Comment by timknowlden** [comment]
2560x1920 is my camera max resolution and the detect resolution on frigate. If I play around with stream settings, I assume I'm best to delete and retrain all images

**Comment by heisenberg2980** [comment]
> Wrong section of min_area
> 
> detect: match: # minimum area in pixels to consider a result a match min_area: 13000

Thanks, that was the issue
