### ISSUE TITLE
Processed events with no matches produce a lot of missed images

### ISSUE THREAD

**Issue by jakowenko** [jakowenko/double-take#33]
@erikarenhill, curious to hear your thoughts on this as well.

I've been testing some of the recent code changes with untrained detectors. One thing I've noticed is that if `SAVE_UNKNOWN` is set to `true`, then a lot of images will be produced for each event. Each retry per detector could produce an image if a person is found. For example, if I'm running compreface and deepstack and the snapshot and latest retries are set to 10 each, then I could in theory have 40 images saved for just a single event.

Maybe just taking a couple of the best results from the unknown images instead of saving out every single one to display on the UI.

![Screen Shot 2021-04-21 at 2 55 17 PM](https://user-images.githubusercontent.com/1081811/115614382-a8d44600-a2bb-11eb-9f48-78d37dc113a5.png)

**Comment by jakowenko** [comment]
Maybe instead of having each detector pull the image, I write the image first and put that image through each detector. It could take a little longer, but would reduce the amount of images in general and Frigate API hits.

**Comment by jakowenko** [comment]
I went ahead and made the changes I mentioned above. Rather than each detector pulling images from Frigate on their own, the image is pulled then passed to each detector. This allows me to reduce the amount of images that are written. Hope this may help with the Frigate API issues too.

**Comment by erikarenhill** [comment]
cool! I actually wrote something similiar about only saving the best matches in #32

**Comment by erikarenhill** [comment]
I'll switch over to beta again and help to try it out

**Comment by jakowenko** [comment]
Awesome, thanks! One thing to note is the UI still displays the same image that was used per detector and if you delete one of the images that was used by another it'll delete both of them. I do want to clean this up still. Maybe displaying one "card" per image and then the results of each detector on that image.

**Comment by jakowenko** [comment]
@erikarenhill let me know what you think about this. Since the same image is now passed to the detectors during each processing loop, I think it makes sense to display all the detection results on the card. It removes all the duplicate looking images when it was previously displayed by detector. Probably need to add a better way to determine which bounding box belongs to which result.

![Screen Shot 2021-04-26 at 2 39 30 AM](https://user-images.githubusercontent.com/1081811/116039408-b3366d00-a638-11eb-83fd-30b0c1aeb65d.png)
