### ISSUE TITLE
New Release Date?

### ISSUE THREAD

**Issue by LordNex** [jakowenko/double-take#335]
Ice noticed some issues with the new Frigate and with err modules that this connects too starting to have issues. After looking I noticed this hasn't been updated in over a year. Is this still actively maintained or has someone else forked off and took over?

**Comment by Haloooch** [comment]
I believe this is the fork most people have now moved over too after Jako stopped maintaining double-take: https://github.com/skrashevich/double-take

**Comment by LordNex** [comment]
> I believe this is the fork most people have now moved over too after Jako stopped maintaining double-take: https://github.com/skrashevich/double-take

Can that be added directly into HA either through the addons store or HACS or do I have to run it in a separate Linux server with docker-compose. I could go either way, I already have Frigate on a separate Linux server with the coral TPU running frigate. But the old version I just added a custom repository in the Add Ins store and loaded it that way.

**Comment by LordNex** [comment]
Found it. Thanks for the link bro!

**Comment by ovizii** [comment]
> Found it. Thanks for the link bro!

Would you mind sharing the link to add this new repository or whatever solution you found? I would also like to switch but can't figure it out.
