### ISSUE TITLE
Add opencv to api url recognize

### ISSUE THREAD

**Issue by amz4u2nv** [jakowenko/double-take#337]
I am using the api to send my own image from the camera, but I would like it to check if the image has faces in it, so i can save the request from going to aws rekognition service.

It would be great to add a parameter to the request to turn on opencv to detect faces prior to sending it to the service.

I'm not sure myself where to begin.

**Comment by codewithriza** [comment]
### **Face Detection Integration using OpenCV**

Hey 

I've got a solution for integrating face detection via OpenCV before triggering AWS Rekognition requests. Here's the plan:

- **API Enhancement:** Add a `enable_face_detection` parameter to the API payload, allowing toggling of face detection.
  
- **Integration Process:**
  - Adjust the API endpoint to handle the new parameter.
  - Incorporate OpenCV's face detection within the API flow.

- **Decision Logic:**
  - When `enable_face_detection` is `true`, perform OpenCV face detection.
  - If faces are found, proceed with AWS Rekognition.
  - If no faces, skip Rekognition to save resources.

- **Considerations:**
  - Seamlessly blend OpenCV within the existing API structure.
  - Assess performance impact and update API documentation.

- **Development Steps:**
  - Discuss implementation specifics with the team.
  - Plan integration steps and devise a robust testing strategy.

Feel free to reach out for further assistance or to discuss details!

**Comment by amz4u2nv** [comment]
That sounds great, well thought out.

**Comment by codewithriza** [comment]
**Thank you** for your positive response! If you encounter any challenges while implementing the solution or need more guidance, please don't hesitate to reach out :)

**Comment by amz4u2nv** [comment]
After more digging looks like opencv does work for the api, but you need to add the cameras section to the config within the detectors section. The if statement maybe in the wrong place
![image](https://github.com/jakowenko/double-take/assets/949924/158b2a33-72f5-4ab1-9173-070844c6fd09)

Thanks
