### ISSUE TITLE
Only latest and beta available at dockerhub + potential bug related to compreface

### ISSUE THREAD

**Issue by erikarenhill** [jakowenko/double-take#44]
Hi,

I noticed only latest and beta is available at dockerhub, not specific versions/releases.

For example my double-take LCX container has crashed and when setting things up again now from scratch I'm experiencing a bug(?) with 0.5.1 and compreface but before reporting it as an actual bug I'd like to check with an older version since I know it has worked before, and not just being some configuration error from my side now. Not having all the tags at dockerhub makes it harder to roll back to a specific version to test this

The thing I'm experiencing is that I get this error in the logs when processing images:
```
compreface process error: Cannot read property 'map' of undefined
```

**Comment by jakowenko** [comment]
You're right. I should be better about having different versions of available on DockerHub. I can build a previous version for you if you want. I'll update my GitHub Action to build latest and the version number maybe.

Are you running [CompreFace v0.5.0](https://github.com/exadel-inc/CompreFace/releases/tag/v0.5.0) now? I wonder if it's related to adding in support for that.

**Comment by erikarenhill** [comment]
> You're right. I should be better about having different versions available on DockerHub. I can build a previous version for you if you want. I'll update my GitHub Action to build latest and the version number for future builds.
> 
> Are you running [CompreFace v0.5.0](https://github.com/exadel-inc/CompreFace/releases/tag/v0.5.0) now? I wonder if it's related to adding in support for that.

I have not changed CompreFace version as that is running on an own lxc container, which means Im running 0.4.1

**Comment by erikarenhill** [comment]
Its working after upgrading compreface to 0.5, thanks for notifying me on that one :)
