### ISSUE TITLE
Timezone/Date format

### ISSUE THREAD

**Issue by erikarenhill** [jakowenko/double-take#5]
Hi, thanks for this awesome project.

I found a couple of issues, as I'm based in Sweden:

Docs are missing for environment variable 'TZ'
Also it would be nice to parametrize the date format, or send the unix timestamp/UTC

**Comment by jakowenko** [comment]
Thank you for the kind words! If you'd like to see any other features added, please let me know.

Good catch on the `TZ` option. I'll get that included in the docs for reference. You should be able to pass it now when the container starts. The default is `America/Detroit`, but I'll probably change that to `UTC` once the other changes go in.

I can add in the option for a date format too. Are you thinking something along the lines of this format (`MM/DD/YYYY hh:mm:ss`) with the ability to change it?

**Comment by jakowenko** [comment]
I've pushed a new build that allows you to configure the time zone and time format and included the defaults in the [README](https://github.com/jakowenko/double-take#options). Let me know if this resolves your issue.

**Comment by erikarenhill** [comment]
Hi @jakowenko  and thanks for such a quick fix, I tested it and just have one minor thing to give feedback for.

I think it might be a good idea to use [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) as default format, at least when using  UTC as default TZ.

Easiest way to incorporate this I believe is to use 'YYYY-MM-DD[T]hh:mm:ss[Z]' as default format (or something like that), as that would give the same output as just using moment().utc().format() without parameters which defaults to iso8601. I could of course just specify this myself by using the environment variable but I think it would make sense to default to this in combination with UTC

As with MQTTv5 this seems to be sent through a "timestamp" property using ISO-8601 format ([source](https://github.com/eclipse/mosquitto/blob/develop/plugins/message-timestamp/mosquitto_message_timestamp.c)) so if also the property name is changed to timestamp instead of time maybe its more futureproof? If I read that code correctly.
Seems to be hard finding out what's the standard to use for mqtt messages....

What do you think?

(Also when using backticks in server.js when logging version and time, the \n is actually escaped and printed instead of becoming a newline :))

**Comment by jakowenko** [comment]
I think using the ISO 8601 format definitely makes sense for UTC and probably just making it the default like you said. If the user wants to change this they would then have the ability to with the `TIME_FORMAT` variable.

Future proofing MQTT and using the `timestamp` property makes sense to me! I'll do a little more reading on this to make sure I understand. I didn't realize MQTT read that value to determine when the message was delivered.

Thanks for all your suggestions, keep them coming! 😄

**Comment by erikarenhill** [comment]
docker logs output do show the correct linebreaks, but the messages.log contains the \n by text
I use a Debian 10 LXC running on top of proxmox with docker-ce 19.03.15. Not a big deal though :)

**Comment by jakowenko** [comment]
Thanks for the clarification. I'll see if I can get that fixed.

**Comment by jakowenko** [comment]
Pushed some updates that should include the changes you suggested if you want to check them out.

If no `DATE_TIME_FORMAT` is passed then it will default to ISO 8601 and supports [token-based formatting](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens) if someone would like to format it differently.

**Comment by erikarenhill** [comment]
> Pushed some updates that should include the changes you suggested if you want to check them out.
> 
> If no `DATE_TIME_FORMAT` is passed then it will default to ISO 8601 and supports [token-based formatting](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens) if someone would like to format it differently.

Awesome! I'm running v0.0.17 now and its working like a charm.

**Comment by sinclairfr** [comment]
Try adding this to your docker-compose.yml file or docker run routine
```
environment:
      - TZ=Europe/Paris
```
