### ISSUE TITLE
mqtt topic state

### ISSUE THREAD

**Issue by Sborkahome** [jakowenko/double-take#50]
Hi! Very cool project! You can modify multiple parts:
1) add a status mqtt topic during start and operation, for example, state = online
Thank you for paying attention to my details!

**Comment by jakowenko** [comment]
Thanks for the suggestion, I can work on getting this added in. What other types of states do you think would be helpful?

**Comment by jakowenko** [comment]
This is now included in v0.6.1. Feel free to reopen if anything needs to be adjusted.

Availability is now published to `double-take/available`
