### ISSUE TITLE
Any way to deal with self signed certs on recognize endpoint

### ISSUE THREAD

**Issue by causefx** [jakowenko/double-take#53]
Trying to send a snap from a camera and I cannot get it to work for the life of me...

`http://docker.home.lab:8203/api/recognize?url=https://10.0.9.40/snap.jpeg`

Getting this error:
```
processing double-take: 2b290cf1-b466-46a7-9774-642e8e724be8
url validation error: self signed certificate
response:
{
  id: '2b290cf1-b466-46a7-9774-642e8e724be8',
  duration: 0.03,
  timestamp: '6/10/2021, 8:06:59 PM',
  attempts: 0,
  camera: 'double-take',
  zones: [],
  matches: []
}
6/10/2021, 8:06:59 PM
done processing double-take: 2b290cf1-b466-46a7-9774-642e8e724be8 in 0.03 sec
```

The camera also has a http endpoint but I'm not sure why it doesn't pass validation...
`http://docker.home.lab:8203/api/recognize?url=http://10.0.9.40/snap.jpeg`

Error:
```
processing double-take: 0f60d94e-0169-4fc5-a269-4adc7b04515a
url validation error: Request failed with status code 400
response:
{
  id: '0f60d94e-0169-4fc5-a269-4adc7b04515a',
  duration: 0.01,
  timestamp: '6/10/2021, 8:10:13 PM',
  attempts: 0,
  camera: 'double-take',
  zones: [],
  matches: []
}
6/10/2021, 8:10:13 PM
done processing double-take: 0f60d94e-0169-4fc5-a269-4adc7b04515a in 0.01 sec
```
Camera is a Ubnt Doorbell camera

**Comment by jakowenko** [comment]
Hey @causefx, updating the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to ignore the certs would probably be quickest fix. I was able to test this locally and verified it worked on a self signed cert. Can you give it a try and let me know if it resolves your issue?

If you're using a Docker compose, just set the environment variable like this.

```yaml
environment:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
```

Or `docker run -e NODE_TLS_REJECT_UNAUTHORIZED='0'`

**Comment by causefx** [comment]
Thanks for the reply @jakowenko 
The cert disabling worked but I still get HTTP error 400 for some reason. 
```
6/10/2021, 9:37:10 PM
processing double-take: 80f07b7b-c256-42fe-9e85-aaf2232a5978
(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
url validation error: Request failed with status code 400
response:
{
  id: '80f07b7b-c256-42fe-9e85-aaf2232a5978',
  duration: 0.09,
  timestamp: '6/10/2021, 9:37:10 PM',
  attempts: 0,
  camera: 'double-take',
  zones: [],
  matches: []
}
6/10/2021, 9:37:10 PM
done processing double-take: 80f07b7b-c256-42fe-9e85-aaf2232a5978 in 0.09 sec
```
I wonder if it has something to do with unifi's end.  The response headers look fine when accessing the url from the browser:
```
HTTP/1.1 200 OK
Content-Type: image/jpeg
Accept-Ranges: bytes
ETag: "2845782448"
Last-Modified: Fri, 11 Jun 2021 04:39:16 GMT
Cache-Control: max-age=1
Content-Length: 226245
Date: Fri, 11 Jun 2021 04:39:15 GMT
Server: lighttpd
```
General info:
```
Request URL: https://10.0.9.40/snap.jpeg
Request Method: GET
Status Code: 200 OK
Remote Address: 10.0.9.40:443
Referrer Policy: strict-origin-when-cross-origin
```
Output:
![image](https://user-images.githubusercontent.com/16184466/121631797-9f05ce00-ca34-11eb-87cd-edd0c6fcdb92.png)

Kinda weird.... I suppose I can do a work around using home-assistant.

**Comment by jakowenko** [comment]
Hm...ya that would make sense since you were also getting the 400 when using the http url. I agree, the headers look good, nothing stands out there.

Could it be a Docker networking issue? You could SSH into the container and try to ping that url.

**Comment by causefx** [comment]
Ping was fine within the container.
Testing with postman I see something...
With Host header:
![image](https://user-images.githubusercontent.com/16184466/121632868-a0d09100-ca36-11eb-9e67-dbc380950c46.png)

Without:
![image](https://user-images.githubusercontent.com/16184466/121632908-ad54e980-ca36-11eb-99e7-39b3b71a371a.png)

**Comment by causefx** [comment]
In the meantime, I went ahead and just creating a small script within one of my other applications:
`http://docker.home.lab:8203/api/recognize?url=http://docker.home.lab:8000/test/test.php`

```
<?php
require_once '../api/functions.php';
$response = Requests::get('http://10.0.9.40/snap.jpeg', [], ['verify' => false]);
if ($response->success) {
	header('Content-type: image/jpeg');
	echo $response->body;
}
die();

```
6/10/2021, 9:57:02 PM
processing double-take: f863e780-fb4d-472a-92b7-d7d3ccf808bd
response:
{
  id: 'f863e780-fb4d-472a-92b7-d7d3ccf808bd',
  duration: 4.31,
  timestamp: '6/10/2021, 9:57:06 PM',
  attempts: 1,
  camera: 'double-take',
  zones: [],
  matches: []
}
6/10/2021, 9:57:06 PM
done processing double-take: f863e780-fb4d-472a-92b7-d7d3ccf808bd in 4.31 sec
```

**Comment by jakowenko** [comment]
Ah, the host header! That's good to know. I can get that updated and include it in all the outbound API requests. Does it seem to be working now with your PHP proxy approach?

**Comment by causefx** [comment]
Yes sir, the temporary php proxy works well.  I will test your solution whenever you get time to update :)

Either way, thanks for taking the time to help 👍🏽

**Comment by jakowenko** [comment]
Great to hear it's working. I'll be out of town this weekend, but will try to get it updated by early next week.

Thanks for checking out this project. If you ever have any feature requests or suggestions, don't hesitate to reach out.

**Comment by causefx** [comment]
No worries man and no hurry.  The project seems really cool - I will def make some FR's once I use it a lot more.  Would you like me to keep this issue open - or close it?

**Comment by jakowenko** [comment]
Thank you, I've had a lot of fun building it over the past few months.

You can keep this open for now. It shouldn't take too much to get that header added in. May just need your help to validate it worked.

**Comment by jakowenko** [comment]
@causefx, it does appear the host header is added by default, so it's got to be something else. Can you try doing the same test in Postman, but set the method to `HEAD`, that's currently what I'm using to do the URL validation. If it fails with the host header and the `HEAD` method, then I will change it over to `GET` to see if that fixes it. If it works, then back to the drawing board haha.

**Comment by causefx** [comment]
Hey again @jakowenko,
![image](https://user-images.githubusercontent.com/16184466/121988417-1c8c4f80-cd4f-11eb-8cad-b7ed502075d0.png)
Error 400...  :)

**Comment by jakowenko** [comment]
Great, I'll push up a fix for that now. Thanks for testing that so quickly.

**Comment by causefx** [comment]
You got it man... I will test once the image is updated :)

**Comment by jakowenko** [comment]
`double-take:beta` just finished building if you want to give that a try. I'll build latest now, but it takes about an hour to finish.

**Comment by causefx** [comment]
ok, let me pull

**Comment by causefx** [comment]
**SUCCESS!!!** 
Good job man!
Thank you!
```
6/14/2021, 9:10:05 PM
processing double-take: 8375bf38-3997-4534-8e96-6c064ca598da
response:
{
  id: '8375bf38-3997-4534-8e96-6c064ca598da',
  duration: 5.43,
  timestamp: '6/14/2021, 9:10:10 PM',
  attempts: 1,
  camera: 'double-take',
  zones: [],
  matches: []
}
6/14/2021, 9:10:10 PM
done processing double-take: 8375bf38-3997-4534-8e96-6c064ca598da in 5.43 sec
```

**Comment by jakowenko** [comment]
Awesome!! Thank you again for helping to test this.

**Comment by causefx** [comment]
No sweat man.  I get my Coral USB in tomorrow, so I will be installing Frigate to test with Double Take.  Once I play around with both, I will be submitting some FR's.

:) thanks again!

**Comment by nanosonde** [comment]
@jakowenko 
Is there any way to set this env var related to the certificates in the HA addon?
