### ISSUE TITLE
min_area_match doesnt seem to be working

### ISSUE THREAD

**Issue by xeryax** [jakowenko/double-take#55]
I am getting a lot of "matches" for faces that are really small (20x20). I have the default set:
`objects:
  face:
    min_area_match: 10000`
but 
![image](https://user-images.githubusercontent.com/26824412/121780615-2ce5d400-cb6f-11eb-945f-c8aebd65986a.png)
these keep being matched...

Also, unrelated... does anyone find that deepstack will take giant leaps at guesses, and compreface always has super certainty on guesses?

**Comment by xeryax** [comment]
just found the beta branch.... can close.

**Comment by jakowenko** [comment]
min_area_match only determines if the result should be a match or not. The image will still be saved to the UI as a miss.

**Comment by jakowenko** [comment]
Closing per your request, let me know if you run into any more issues or have questions.
