### ISSUE TITLE
train/add/name not working

### ISSUE THREAD

**Issue by Alfiegerner** [jakowenko/double-take#62]
Hi,

Congrats on the new version, looking really nice.

Just coming back to play with this and ran into an error with the train feature. I've used this functionality before with success, but having issues with v.90.

I can see inside the docker shell that storage is set up correctly, i.e. within the docket OS I can see files at /.storage/train/alex. But when I try and load this via a post call:

`curl --location --request POST 'localhost:3010/api/train/add/alex'`

I get 0 files queued:

```
info: alex: queuing 0 file(s) for training
info: alex: training complete in 5.21 sec
```

This is starting with clean (deleted) database.db.

Any idea what I might be missing?

**Comment by jakowenko** [comment]
Hey @Alfiegerner, any chance those images were already trained at one point? That endpoint won't retrain them, there's a different one for doing that, I'll need to update the Postman docs to show that.

When you pull up the UI and go to the "Train" tab, do you see any images?

**Comment by Alfiegerner** [comment]
They were trained on a previous version of the app, but I've deleted the database.db to clear the persisted trained data.

I can see images from e.g. train/alex under the Train tab of the UI.

Just tried the retrain API call and getting

```
<tiitle>Error</title>
</head>
<body>
<pre>Cannot GET /api/retrain/alex</pre>
```

Also tried with POST and PUT with same results.

Thanks for looking @jakowenko .

**Comment by jakowenko** [comment]
It should be GET - `/train/retrain/:name`, your example is missing the `train` param. Here's the [link](https://github.com/jakowenko/double-take/blob/master/api/src/routes/index.js#L40) to it in the code so you can see what the other routes are too.

**Comment by Alfiegerner** [comment]
That worked! Thanks @jakowenko !

**Comment by jakowenko** [comment]
> That worked! Thanks @jakowenko !

Yay! You're welcome.

**Comment by maxi1134** [comment]
Hi there,

I am experiencing this problem too!

I post to train "mikemyers" and it says it's queued, but the name never seems to be taught.
The name doesn't appear in the name list, and it's not matched when the same image is passed back.

Here a few images to help debug!

![image](https://user-images.githubusercontent.com/1342643/129137210-1e6fc3e3-0259-4795-8562-511fe527bb06.png)
![image](https://user-images.githubusercontent.com/1342643/129137262-319f0284-710b-4d86-a8c3-df2e9a891889.png)
![image](https://user-images.githubusercontent.com/1342643/129137270-c0b69a49-fd25-4c4c-9a2d-ca35d43d0037.png)


Thanks for reading!
