### ISSUE TITLE
Frigate Error - Connection already opened

### ISSUE THREAD

**Issue by dimitribellini** [jakowenko/double-take#69]
After i have finally a Double Take instance work, thanks to Jako, i now come in this scenario.
My Frigate docker container inside the "homeassistant OS" after some time (2/3 hours) seems freezed, looking to the container logs i can see a lot of message like:

------------------------------------

`2021-08-03T11:21:16Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '40420', 'HTTP_HOST': 'ccab4aaf-frigate', (hidden keys: 24)} failed with OperationalError
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/dist-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_sockets.py", line 48, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/opt/frigate/frigate/http.py", line 89, in _db_connect
    database.connect()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3061, in connect
    raise OperationalError('Connection already opened.')
peewee.OperationalError: Connection already opened.`

------------------------------------
This kind of problem seems something related to Frigate and DoubleTake as i can read from this issue https://github.com/blakeblackshear/frigate/issues/920. 

@jakowenko What do think about it?
Thanks so much

**Comment by jakowenko** [comment]
Hey @dimitribellini, what is your `frigate.attempts.snapshot` set to? If you're running Frigate v0.8.X I'd recommend setting it to `0`, which it should be by default. There did seem to be a connection issue with the Frigate API that would cause it to crash. Setting snapshots to `0` fixed that for me. I'm running the beta version of Frigate v0.9.0 and that issue seems to be fixed, so you can safely increase the snapshot count if desired.

**Comment by dimitribellini** [comment]
Hi Jako,
thanks so much, as i usually i made a wrong configuration... :-)
below my original conf of DoubleTake:
`  attempts:
    latest: 5
    snapshot: 5`

I have add "snapshot to 5" only because i have notice that some camera do not receive "snapshot" from Frigate, have you never saw that case?
Thanks so much

**Comment by jakowenko** [comment]
Remove snapshots for now from your config and that should stop Frigate from crashing.

There's three types of images Double Take will process from Frigate.

The MQTT snapshot image, which is different than the one we are talking about above and then the `latest.jpg` and `snapshot.jpg` image which comes from the actual event.

Frigate seemed to have a connection bug when processing that `snapshot.jpg` image. Just remove it from your config for now and it'll default to `0`. Once Frigate v0.9.0 is released, I'll increase the default back to `5`.

**Comment by dimitribellini** [comment]
Ok, i follow your suggestions :-)

What about the problem of not receiving all "events" coming from Frigate? Is probably related to the "connection" problems?
Thanks

**Comment by jakowenko** [comment]
Have you verified that Frigate is publishing to the snapshot topics for the cameras that are missing? Double Take just watches for messages on those topics and then will process the image.

**Comment by dimitribellini** [comment]
Yes the snapshot is coming from Frigate, i use this command:
`mosquitto_sub -h 192.168.0.40 -u xxxx -P xxxx -v -t frigate/<CAMERA>/person/snapshot`

but on DoubleTake i did not see all the "snapshots" image, sometime yes sometime no :-)

**Comment by jakowenko** [comment]
Is there a chance that no person was found in that image so it was never saved by Double Take?

**Comment by jakowenko** [comment]
You should be able to look at the raw logs and see if MQTT messages are being processed for those cameras. They logs are in `/.storage/messages.log'

**Comment by dimitribellini** [comment]
Hi Jako, i have checked:
```
[root@ai-vm ~]# tail -f .storage/messages.log|grep ufficio
21-08-04 13:24:44 info: processing ufficio: 1628083463.127387-oi99t2
21-08-04 13:24:44 info: processing ufficio: defd7c46-478d-436c-8f97-611ae569df35
21-08-04 13:24:44 info: done processing ufficio: defd7c46-478d-436c-8f97-611ae569df35 in 0.09 sec
  camera: 'ufficio',
21-08-04 13:24:44 info: done processing ufficio: 1628083463.127387-oi99t2 in 0.51 sec
  camera: 'ufficio',
21-08-04 13:24:48 info: processing ufficio: 1628083463.127387-oi99t2
21-08-04 13:24:49 info: done processing ufficio: 1628083463.127387-oi99t2 in 0.4 sec
  camera: 'ufficio',
```
But on DoubleTake frontend i did not see some snapshots of these specific events.

**Comment by jakowenko** [comment]
Is there a chance no person was found in the image?

**Comment by dimitribellini** [comment]
Yes the message seems "void":

```
21-08-04 13:26:45 info: done processing ufficio: 1628083601.123101-fms3tm in 0.5 sec
21-08-04 13:26:45 info: {
  id: '1628083601.123101-fms3tm',
  duration: 0.5,
  timestamp: '8/4/2021, 3:26:45 PM',
  attempts: 8,
  camera: 'ufficio',
  zones: [],
  matches: []
}
```

But it's strange because i was moving in front of the camera...
![image](https://user-images.githubusercontent.com/16684861/128190816-f03d7a34-ea30-4630-9c76-0fd3fceb61e2.png)

**Comment by jakowenko** [comment]
Try doing it again and look at the camera for a few moments just to see if it gets you. It's not going to be perfect 100% of the time, but I'm surprised Frigate's MQTT snapshot image didn't have a better picture of you.

**Comment by dimitribellini** [comment]
Try doing it again and look at the camera for a few moments just to see if it gets you. It's not going to be perfect 100% of the time, but I'm surprised Frigate's MQTT snapshot image didn't have a better picture of you.

>> Me too, but seems Frigate do not send all the snapshots of an "event"

That's also a tiny image, is that just the thumbnail for Frigate event?

>> Yes correct, is the image of the Frigate thumbnail

Try turning on "live reload" on the UI as well so images come in without needing to refresh while you are testing.

>> Ok i will test it

Thanks so much
