### ISSUE TITLE
docs: Node-Red example / save match to home assistant media-directory

### ISSUE THREAD

**Issue by erikarenhill** [jakowenko/double-take#7]
It would be very nice with a documented example how to send notifications with attached photo as shown in the github readme.
From what I understand you can fetch the image from {FRIGATE_URL}/clips/{msg.payload.camera}/{msg.payload.id}.jpg is this the preferred way, or do you store the photo to home assistant first somehow?

**Comment by jakowenko** [comment]
I will prioritize getting the README updated with more complete examples.

Any time a match is found the image is saved to this path `./storage/matches/{name}/{id}-{type}.jpg` and they are served from the API via `http://localhost:{PORT}/storage/matches/{name}/{id}-{type}.jpg`

If the image came from Frigate then the type would either be `latest` or `snapshot` depending on which image it found a match in. For matches that came from hitting the `/recognize` endpoint directly, the images have a type of `manual`.

These images are stored currently for 48 hours and deleted via a cron job that runs once an hour. I probably need to allow the user to specify how long they would like to retain images for, but that current logic is [here](https://github.com/jakowenko/double-take/blob/master/src/util/storage.util.js#L8). I also need to include information about this in the README.
