### ISSUE TITLE
status code 401

### ISSUE THREAD

**Issue by arcidodo** [jakowenko/double-take#70]
latest version:

21-08-07 08:50:50 error: Request failed with status code 401
21-08-07 08:50:50 info: arco: queuing 0 file(s) for training
21-08-07 08:50:50 info: arco: training complete in 0.04 sec

i get this error, i cannot train. 
manual upload an image is working tough. 

beta:
yesterday i installed the beta version and i get this error:

21-08-06 18:56:25 error: Error: save url error: Request failed with status code 401
    at createError (/double-take/api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/double-take/api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/double-take/api/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
21-08-06 18:56:25 info: arco: queuing 0 file(s) for training
21-08-06 18:56:25 info: arco: training complete in 0 sec

config:

# Double Take
auth: true

mqtt:
  host: 10.0.102.100
  username: ***
  password: ***

frigate:
  url: http://10.0.102.100:5000
  image:
    height: 500
  attempts:
    latest: 10
    snapshot: 0
  cameras:
    - achtertuin
    - oprit
    - deurbel
    
detectors:
  compreface:
    url: http://10.0.102.100:8000
    key: ***

**Comment by jakowenko** [comment]
Hey @arcidodo, this should be fixed in the beta build that I just pushed. I missed adding an auth token to one of the calls if authentication is enabled. Let met know if that fixes it for you.

**Comment by arcidodo** [comment]
Yes it is working! thx. but in the previous version the pictures in the matches section moves to the train tab if you train it to an person. but now it stays on both pages is this correct?

**Comment by jakowenko** [comment]
> Yes it is working! thx. but in the previous version the pictures in the matches section moves to the train tab if you train it to an person. but now it stays on both pages is this correct?

Yes, that's correct. It just copies the image over.
