### ISSUE TITLE
/tmp filling up inside container - system does not purge automatically

### ISSUE THREAD

**Issue by poweredgenl** [jakowenko/double-take#76]
im noticing some behaviour specific in the /tmp folder of the double-take container. i noticed this because suddenly the directory becomes 10's of gbytes in size and the OS runs out of disk space.

Is this natural? some of the files i see in this dir:

1629476245.068447-s3lhd2-latest-4d0196c0-0698-4dc9-8560-c2f250f6fd2c.jpg            fece6499-e89a-45fb-b34f-56df5c27bec7.jpg
1629476245.068447-s3lhd2-latest-4d6c54eb-ebe4-4ce8-986d-932f624e42c3.jpg            fed7133a-879e-4d71-8746-54b6e83338c0-mqtt-3a8f2fd5-4de7-45b8-9409-09eb1af130d7.jpg
1629476245.068447-s3lhd2-latest-54723bc1-79eb-4453-90d7-2babd1831194.jpg            fedcda88-94f0-4980-8f75-a6042cdd5cad-mqtt-0c00db20-50c0-458f-b996-e6cdd0eb7dd6.jpg

bash-5.0# ls -l | wc -l
114848

I think this should be the case / beeing that large. I could remove it manually i think, but last time i stopped the container rmi/rebuild it to get rid of the issue. 

Setup: 6 cams running with 5 fps / 1080p reso - purge 168 setting. (fyi didnt had this issue before - using it already some time). Double take v0.10.1

Views anyone?

**Comment by jakowenko** [comment]
Hey @poweredgenl, thanks for reporting this issue you're having. Images are written to the /tmp folder before being processed, but I mistakenly thought the OS would handle cleaning up that folder when disk space was high. It seems like depending on the distro you're running on it's handled differently.

I'll probably need to include a cron job to delete images from that folder that are more then X minutes old.

The purge setting right now only includes the /matches folder and not the /tmp one.

Open to suggestions on how to handle this if you have a better idea than a cron.

**Comment by poweredgenl** [comment]
Hi @jakowenko .. thnx for the insight. So the dir i@ not needed for post processing...

Im not a native coder so suggestions are a bit so so..

1 use a cron...pro ..scheduled less constraints in processing..batch driven thus with high load not additional resource consumption...cons...with lot of files..system could prevent rm rf...like in my case...
2 transaction driven...could you implement a per transaction check and sent the tmp file along and let the processing transaction immediately delete the file afterwards?

Other thought...could it be that due to perhaps a detector not beeing available...it queues the transactions and thus filling up /tmp? How did you designed this situation aka behavior? If so.. a check it will not queue up those files in /tmp?

Your view? :)

**Comment by jakowenko** [comment]
I like the idea of transaction driven, after each event I'll delete the tmp image. Maybe on start I'll delete all tmp images too just incase any ever get orphaned due to an error.

**Comment by poweredgenl** [comment]
> I like the idea of transaction driven, after each event I'll delete the tmp image. Maybe on start I'll delete all tmp images too just incase any ever get orphaned due to an error.

Would be my preference too, transaction driven, in case a lot of movements aka detection occurs you want to finish the crud process in 1 flow rather then splitting. Keep me posted when you want to test..

**Comment by jakowenko** [comment]
Just pushed a new build to `jakowenko/double-take:beta` if you want to try it out. All processed images are now saved to `/tmp/double-take` and are deleted after processing. On server restarts the entire folder is deleted and recreated for extra cleanup.

**Comment by poweredgenl** [comment]
Great! Will test tonight after work so expect a bit delay...CET timezone over here.

**Comment by poweredgenl** [comment]
looks like disk is not beeing filled up anymore... so a close from me ...

**Comment by jakowenko** [comment]
I have a fix ready, there was a feature that introduced a bug that caused the tmp images to not be deleted. I can update the path to ` /dev/shm` though if that's better. Is there any issues with writing to ` /dev/shm` that I need to account for?
