### ISSUE TITLE
unauthorised error using API

### ISSUE THREAD

**Issue by kanemari** [jakowenko/double-take#80]
hi there,

I have enabled authentication on the UI which I understand is also meant to enable authentication on the API.

I have validated that the HA entities for double_take_name have the token attribute in them, and that HA is passing token={{trigger.to_state.attributes.token}} into the image URL, but I always get an 'unauthorised' error.

have tried manually pulling the attributes from the HA sensor and manually recreating the URL using filename and token, and it comes back with 'unauthorised' as well.

what is the best way to troubleshoot?

**Comment by jakowenko** [comment]
Hey @kanemari, I pushed a new beta build with the ability to adjust this. I'm defaulting it to `24h` currently, but can be adjusted by adding this to your config. The value is expressed in seconds or a string describing a time span [zeit/ms](https://github.com/vercel/ms). Let me know if this resolves your issue.

```yaml
token:
  image: 24h
```

**Comment by kanemari** [comment]
cool, thanks! will test this coming weekend when I get some time.

stupid question, but how can I pull the beta branch through docker?

**Comment by jakowenko** [comment]
> cool, thanks! will test this coming weekend when I get some time.
> 
> stupid question, but how can I pull the beta branch through docker?

This is the beta Docker image `jakowenko/double-take:beta` you can use.

**Comment by kanemari** [comment]
appears to be working!
