### ISSUE TITLE
Question: Compatible with Compreface 0.6.0

### ISSUE THREAD

**Issue by mi4mac** [jakowenko/double-take#82]
Hi Jakowenko,

is your beta release already compatible with compreface 0.6.0?

Thanks in advance

**Comment by jakowenko** [comment]
Hello @mi4mac,

Yes, both the latest and beta Docker images should work with CompreFace `0.6.0`. I'm running it on my personal setup and haven't had any issues.

If you run into any problems, feel free to open a new issue.
