### ISSUE TITLE
Beta-Versioning on Docker. What is the latest/Update available?

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#86]
i pull the beta from docker, but it says there is an update available.
somehow unclear what ist the "really" latest. may there would help a clearer versioning?

![image](https://user-images.githubusercontent.com/5937811/132087695-d76c355d-b212-4dcb-95a8-64c7e7385313.png)

**Comment by jakowenko** [comment]
I pushed a new beta built last night with a bug that I didn't have time to fix, so I had run a previous build to not have a broken beta published. I removed the GitHub builds in question, so the update icon should go away now.
