### ISSUE TITLE
Enhancement: Gui-Selection of Train-Images

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#89]
On the train-Tab i can select the folder for the Person/Face.
But the page shows only general all images, regardless of that selection.

I would like to see only images for a selected Person/Folder. 
May there can be a selector? (the sync-button does not help)

(and maybe for DEBUG on the config-page the doubl-take version for simple copyANDpaste ?
i am on latest beta today, but lack some versioning-nr..)

![face-select](https://user-images.githubusercontent.com/5937811/132123579-3982044a-f972-43a2-90f4-f9e7e0ebf386.gif)

**Comment by jakowenko** [comment]
I've updated the training page to filter the results when the dropdown is used and also pushed an UI change to the training page to allow you to quickly copy the version. Here's a screenshot of how it looks. When you hover and click it should copy to clipboard.

![Screen Shot 2021-09-06 at 11 51 20 PM](https://user-images.githubusercontent.com/1081811/132281718-fb2095d8-710f-4644-82ee-e227da031e67.png)

**Comment by ozett** [comment]
Great, thanks! its working.
Now i have the config in double-take 😄 
I had to do a explicit pull to grab the new docker-image. 
maybe because versioning has not changed?

![image](https://user-images.githubusercontent.com/5937811/132311451-4faf4957-d074-4f26-956d-288c98a4c7d8.png)

May the selection for the dropdown could be configured in the configuration?
maybe not everybody likes this like me as a general default?

**Comment by jakowenko** [comment]
@ozett new take on this idea. You can still click on the "Double Take" text to copy the version, but I don't display it anymore since it's also in the dropdown with a link to Github. I also added a button to copy the entire config and it redacts any passwords or secrets when doing so.

Should make it easier to share a config if it's needed for debugging.

![Screen Shot 2021-09-09 at 2 06 48 AM](https://user-images.githubusercontent.com/1081811/132632045-7b8512ce-f7ef-4318-b92b-aa6e4c26dc58.png)

**Comment by ozett** [comment]
the result of the click-function is helpful.
but very secret to find... 
How do one know to click there and dont expect something dangerous?

![image](https://user-images.githubusercontent.com/5937811/132671578-dfcc5102-7732-4f34-a23e-73cfdb99d1fd.png)

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/132882419-5c62132b-a6c4-4462-9f53-15f402383f65.png)
putting new training images into the folder results in untrained images on the match-page.
all clicked and synced results in "untraining" and "trainig" again.

using the checkbox one-by-one for training results in queue-jobs for training.
would like to queue multiple images from the gui and omit the "untrainig" of all registered images.. 

do you think thers is a way?

**Comment by jakowenko** [comment]
I realize this may be a bit confusing, I'll try to explain how it works.

You can always train single/multiple images towards a new person or existing person without affecting the currently trained images. Adding new images to the train folder manually just puts them on the trained page under that user in an "untrained" state.

Not all the detectors support just untraining a single image though, so my workaround when you remove an image from someone, is to remove all existing images, then retrain that user with just the new images.

The sync button is really just a way to "resync" everything from the train folder for that user. You don't need to select any photos when clicking it. It works similar to removing everything for that user, then readding it all. This is helpful to me when I test things and want to make sure there's not orphaned data on the detectors.

**Comment by jakowenko** [comment]
Closing since this is now included in the `1.0.0` release.
