### ISSUE TITLE
Not processing MQTT events from Frigate

### ISSUE THREAD

**Issue by ralphmackinder** [jakowenko/double-take#93]
Really weird issue - all setup fine, it connects to MQTT, sees frigate/events and frigate/+/person/snapshot topics. 

Ive trained faces fine, but when the MQTT topics in frigate are updated, nothing happens. No errors, and no processing. 

I see the double-take/ topic in my MQTT server, but it just shows 'online' and isnt publishing any new sensors in Home assistant for my trained faces. 

Any advice on what this could be? To confirm, doubletake / detector / MQTT all connected and 'green' in config.

**Comment by ralphmackinder** [comment]
closing issue - it was a config error in the MQTT section. the syntax in the readme vs the formatting on the config yml is slightly different.

**Comment by jakowenko** [comment]
> closing issue - it was a config error in the MQTT section. the syntax in the readme vs the formatting on the config yml is slightly different.

What was different in the syntax? I'll make sure to update the README to correct it.

**Comment by ralphmackinder** [comment]
Hi, it was the mqtt username and password. I copied and pasted the 'mqtt.username' instead of just using 'username' under the mqtt indent. 

Not really an error with the readme just slightly confusing. I think there is an another closed issue which is almost identical. 

Everything is now working, except I dont see any images under 'matched' on the GUI. The images are in the .storage volume, but not showing. Any ideas on that?

**Comment by jakowenko** [comment]
FYI - I overhauled the configuration part of the docs and some of the settings to make it easier to see. The confusing table is gone now. Everything should be [here](https://github.com/jakowenko/double-take/tree/beta#configuration).

Hm, do you want to jump on Discord and I can try to help you? If you see images in `.storage/matches` then they should be showing up in the UI.

**Comment by ralphmackinder** [comment]
Hi Tried to join the discord but couldnt for some reason. do you have a invite link?
