### ISSUE TITLE
FR Config-check?

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#94]
after editing  the config from the gui i realized no matches after some hours.
restarting did not help. so i checked to logs by incident. that was luck.
maybe a pre-start parser is needed? 

i have it runnng, but could be hard for noobs...

![image](https://user-images.githubusercontent.com/5937811/132876054-a4af25c5-1608-4c29-8c63-003925604d4e.png)

**Comment by jakowenko** [comment]
I'll look to see if I can parse the config from the UI before saving it to catch this and return an error if it's invalid. It doesn't seem like it should be too hard to add in.

Thanks for suggesting this.

**Comment by jakowenko** [comment]
I was able to catch the error before writing the file so it can be displayed on the UI.
![Screen Shot 2021-09-10 at 8 12 14 PM](https://user-images.githubusercontent.com/1081811/132929421-36ea2f89-1656-4419-874c-45ef43d4a5c3.png)

**Comment by ozett** [comment]
when a config-error (or typo) becomes visible before going to disk - it is an improvement

**Comment by jakowenko** [comment]
Closing as this was merged into release `1.0.0`
