### ISSUE TITLE
Question: Serious Warning - or only information? label is CAT or cow

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#95]
i got log infos like: `` label not a person, cow found```

regardless of the label. is the image processed?

![image](https://user-images.githubusercontent.com/5937811/132904226-a6251000-abf3-4ed5-b420-1520a34f1450.png)

**Comment by jakowenko** [comment]
No, those images are not being processed. There is a Frigate [label check](https://github.com/jakowenko/double-take/blob/master/api/src/util/frigate.util.js#L52) that happens first to make sure the label is a person.

I can remove these though, or maybe hide them under another log level type. I'm working on adding verbose logs. So maybe this should be hidden by default.

**Comment by jakowenko** [comment]
I moved these warnings to a new log level type that I just added support for. See more [here](https://github.com/jakowenko/double-take/tree/beta#logs).

By default these won't show now unless the logger is set to `verbose`.

**Comment by ozett** [comment]
i would like to see this configurable.
maybe you let the user overwrite the category? or add more object-types for face-red?

if i can use other object-categories to feed into face-detect helps for me to catch som typical false-positives.
(i do this on my custom-python also for false-positives. the object-category is not always correct)

**Comment by jakowenko** [comment]
It supports various categories, but I need to add code to log for each of those various ones and depending on what level is set you'll either see them or not. This is just adding support for more of that in the future.

What idea did you have to overwrite the categories? Can you post a sample config of what you had in mind?

**Comment by ozett** [comment]
behind my cat-category sometimes is a human face. 
i would like to feed that image to the fac-rec, regardless is was tagged as cat.
than the face-rec will sort it out.

the way it now works is, that the categroy will sort (false-false-positive) images tagged with cat out. but sometimes they contain faces. i would let the face-rec do this work on not fully rely on obj-detection by categro. or at least let the user choose in the config to do such thing.

**Comment by jakowenko** [comment]
Ah I see what you mean. So maybe something like this in the config? Then the user can define what labels they want to process images for?

```yaml
frigate:
   labels:
    - person
    - cat
    - dog
```

**Comment by ozett** [comment]
looks good.
syntax like in frigate..

```
# NOTE: Try to Find FACES in images with other object-labels. Use Labels for FACE-REC:
frigate:
   labels:     
     - person
     - cat
     - dog
```


sould be made clear (somehow), that this is opens up the first narrow object-selction in frigate with a second-selection "opener" to a second-level face-analysis (to find faces in therefore false-positive-categories)

**Comment by jakowenko** [comment]
I'll try to work this in the beta build tomorrow. It's 3:30am here. I'm off to bed for the night 😴

**Comment by ozett** [comment]
alrigth. in europe now daytime started ... ✋

**Comment by jakowenko** [comment]
I snuck this in before going to bed. Let me know if this works.

```yaml
frigate:
  url: http://localhost:5000
  labels:
    - person
    - cat
```

Logs will now show something like this too.

![Screen Shot 2021-09-11 at 4 06 02 AM](https://user-images.githubusercontent.com/1081811/132941147-ef065a25-53fa-4714-a2a0-7ad423a09b1c.png)

**Comment by ozett** [comment]
MQTT sub does not reflect this. i wait for more logging...

![image](https://user-images.githubusercontent.com/5937811/132941943-ef2d327f-95fa-4647-a0e5-6dbad4fb7376.png)

**Comment by jakowenko** [comment]
What do you mean the MQTT subscription is not reflecting it? If the processed image with a cat doesn't return a match or unknown person then nothing will be published to.

Set your logs to see and see if anything shows up for those labels. In my testing the label check is working. Everything after that is what was previously happening with the processing of that image.

```yaml
logs:
  level: verbose
```

**Comment by ozett** [comment]
i assume your getting snapshot from the topic: ```/+/person/snapshot```
but thats only person.

the cats from every cam would be: ```/+/cat/snapshot```

my proof:
![image](https://user-images.githubusercontent.com/5937811/132951444-b022c044-21a5-48b4-bbb0-27d1688bcd22.png)

**Comment by ozett** [comment]
face on bicycle - worth checking... 😄 

![image](https://user-images.githubusercontent.com/5937811/132952530-3504db45-90bf-4f77-af29-e4635498c4d5.png)

**Comment by ozett** [comment]
i am on "v1.0.0-d25c1fd:beta" and guess that face-rec is still limited to "person" categories because DT still only listens to the fixed MQTT-topic "person". 

or am i wrong with that? does DT grab  the configured other labels from the other event-topic (cat ...) and grabs them than over http as "snapshot"? https://github.com/jakowenko/double-take/tree/beta#frigate-1

**Comment by jakowenko** [comment]
> i am on "v1.0.0-d25c1fd:beta" and guess that face-rec is still limited to "person" categories because DT still only listens to the fixed MQTT-topic "person".
> 
> or am i wrong with that? does DT grab the configured other labels from the "**event**"-topic and grabs them than over http as "snapshot"? https://github.com/jakowenko/double-take/tree/beta#frigate-1

The labels are only used when DT is triggered from frigate/events. It doesn't apply to the other snapshot topics. If you would like support for this can you open a new issue?

I'm trying to clean up some of these legacy ones now that `1.0.0` was released and had changes for this issue.
