### ISSUE TITLE
mqtt message - base64 image

### ISSUE THREAD

**Issue by Haloooch** [jakowenko/double-take#96]
I'm in two minds about this one, particularly given I've just written a lot of node-red code to make it all work.

Should the original Frigate mqtt message id be included in the double-take mqtt message? Why, I have just setup automation to save the double-take base64 image to local storage, I then reference it through mobile notifications. However, it occurred to me, Frigate has already processed the image and saved it to storage, I'm just doubling up resources. If I had the original Frigate id I could just pull the image frigate has already stored.

Adding benefit would be hugely reducing the size of the double-take mqtt message.

**Comment by jakowenko** [comment]
Hey, I can definitely add support for this. It should be easy. The` base64` in the message can then be disabled in your config once I add in the Frigate ID.

Also as an FYI. I just pushed a decent config update to the beta build. This adds a more unified global detect config object with the ability to override it at a camera level too.

I have every example detailed out [here](https://github.com/jakowenko/double-take/tree/beta#configuration).

I'll try to get the Frigate ID added in within the hour.

**Comment by jakowenko** [comment]
I just looked at the code and the ID returned should be the Frigate ID. If the event is from Frigate, then that is the ID the API uses in the response and MQTT message.

**Comment by Haloooch** [comment]
lol, wish I had checked that 2 days ago when I started on my new automations :)
Will try this and then take out the base64 flag. Thx.

**Comment by jakowenko** [comment]
I'm going to close this since everything has been released in `1.0.0`. Feel fee to open a new issue if you run into problems.
