### ISSUE TITLE
beta: mqtt missing bounding box (v1.0.0-482b7c9:beta)

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#97]
i am pretty sure that the matches over mqtt had a bounding box..
is it gone?

![image](https://user-images.githubusercontent.com/5937811/132952821-2e65443c-3b74-44d5-bb92-9ebb9acef7ff.png)

**Comment by jakowenko** [comment]
Do you have `base64: box` defined in the `detect` object? I just tested it and the `base64` result had the bounding box.

```yaml
detect:
  match:
    base64: 'box'
```

![Screen Shot 2021-09-11 at 11 32 38 AM](https://user-images.githubusercontent.com/1081811/132953153-6ab80310-0486-4a6d-8694-64ee7037f609.png)

**Comment by ozett** [comment]
you are right. i copied the new syntax-example that stated "true" predefined.
i changed it now to ```box```.
as far as i remember it is ```bbox``` in frigate, isnt it?

![image](https://user-images.githubusercontent.com/5937811/132953873-18151d22-0455-4451-9bcc-1246f442e81f.png)

**Comment by jakowenko** [comment]
Yes, they refer to it as `bbox`. Do you think I should do the same?

**Comment by ozett** [comment]
as double-take is somehow closer bound to frigate its easier not to have slight similar (but still different) option-names.
may you keep options-names close to frigate an use bbox or at least allow both writings (box,bbox) ?

**Comment by jakowenko** [comment]
Closing this for now since all these changes are in the `1.0.0` release. Feel free to open a new issue if something isn't working.
